# Generated by Django 4.2.4 on 2023-09-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(default='hotel.jpg', upload_to='categoryimages'),
        ),
    ]
