# Generated by Django 4.2.4 on 2023-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
