# Generated by Django 4.2.4 on 2023-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
